import os

from dotenv import load_dotenv
from groq import Groq


MODEL_NAME = "openai/gpt-oss-20b"


class LLMGenerator:

    def __init__(self):

        load_dotenv()

        api_key = os.getenv("GROQ_API_KEY")

        if not api_key:
            raise ValueError(
                "GROQ_API_KEY is missing from .env"
            )

        self.client = Groq(
            api_key=api_key
        )

        print("LLM Generator initialized")


    def generate(self, prompt):

        response = self.client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.2,
            max_tokens=1000
        )

        return response.choices[0].message.content.strip()


if __name__ == "__main__":

    generator = LLMGenerator()

    test_prompt = """
You are a DevOps troubleshooting assistant specialized in Docker.

Answer using ONLY the provided documentation.

User question:
My Docker container loses data after restart.

Documentation:
Docker volumes are the preferred mechanism for persisting
data generated by and used by Docker containers.

If you use volumes or bind mounts to store container data,
the data can persist independently of the container.

Give a concise technical answer.
"""

    print()
    print("=" * 70)
    print("GENERATING ANSWER")
    print("=" * 70)

    answer = generator.generate(test_prompt)

    print()
    print(answer)
    print()