class PromptBuilder:

    def build(self, query, results):

        context_parts = []

        for i, result in enumerate(results, start=1):

            context_parts.append(
                f"""
SOURCE {i}: {result['source']}

{result['text']}
"""
            )

        context = "\n".join(context_parts)

        prompt = f"""
You are a DevOps troubleshooting assistant specialized in Docker.

Answer the user's question using ONLY the provided Docker
documentation context.

If the context does not contain enough information to answer
the question, clearly say that the documentation does not
provide enough information.

Do not invent commands, configurations, or explanations that
are not supported by the documentation.

Give a clear and practical answer.

User question:
{query}

Documentation context:
{context}

Instructions:
- Explain the likely cause.
- Give the recommended solution when supported by the documentation.
- Include relevant Docker commands when they appear in the context.
- Keep the answer concise and technical.
- Mention the relevant documentation sources.
"""

        return prompt


if __name__ == "__main__":

    builder = PromptBuilder()

    query = "My docker container loses data after restart"

    results = [
        {
            "source": "volumes.md",
            "text": (
                "Volumes are the preferred mechanism for persisting "
                "data generated by and used by Docker containers."
            )
        },
        {
            "source": "backup-and-restore.md",
            "text": (
                "If you use volumes or bind mounts to store your "
                "container data, the data can persist independently "
                "of the container."
            )
        }
    ]

    prompt = builder.build(
        query,
        results
    )

    print("=" * 70)
    print("GENERATED PROMPT")
    print("=" * 70)
    print(prompt)
