import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# Project root: devops-troubleshooting-assistant/
PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = PROJECT_ROOT / "data"

MONITORING_FILE = DATA_DIR / "monitoring.jsonl"
FEEDBACK_FILE = DATA_DIR / "feedback.jsonl"


def _ensure_data_directory() -> None:
    """Create the data directory if it does not exist."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)


def _append_jsonl(file_path: Path, data: dict[str, Any]) -> None:
    """Append one JSON object as a single line."""
    _ensure_data_directory()

    with file_path.open("a", encoding="utf-8") as file:
        file.write(json.dumps(data, ensure_ascii=False) + "\n")


def _read_jsonl(file_path: Path) -> list[dict[str, Any]]:
    """Read all JSON objects from a JSONL file."""
    if not file_path.exists():
        return []

    records = []

    with file_path.open("r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()

            if not line:
                continue

            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                # Ignore malformed lines instead of breaking monitoring.
                continue

    return records


def log_request(
    query: str,
    latency: float,
    category: str | None = None,
    retrieval_scores: list[float] | None = None,
    rerank_scores: list[float] | None = None,
    rewritten_query: str | None = None,
) -> None:
    """
    Log one RAG request.

    Parameters:
        query:
            Original user query.

        latency:
            Total RAG response time in seconds.

        category:
            Optional problem category.

        retrieval_scores:
            Optional RRF/hybrid retrieval scores.

        rerank_scores:
            Optional cross-encoder reranking scores.

        rewritten_query:
            Query generated by the query rewriter.
    """

    record = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "query": query,
        "rewritten_query": rewritten_query,
        "latency": round(latency, 4),
        "category": category,
        "retrieval_scores": retrieval_scores or [],
        "rerank_scores": rerank_scores or [],
    }

    _append_jsonl(MONITORING_FILE, record)


def log_feedback(
    query: str,
    rating: str,
    comment: str | None = None,
) -> None:
    """
    Log user feedback.

    rating should normally be:
        positive
        negative
    """

    if rating not in {"positive", "negative"}:
        raise ValueError(
            "rating must be either 'positive' or 'negative'"
        )

    record = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "query": query,
        "rating": rating,
        "comment": comment,
    }

    _append_jsonl(FEEDBACK_FILE, record)


def get_monitoring_records() -> list[dict[str, Any]]:
    """Return all monitoring records."""
    return _read_jsonl(MONITORING_FILE)


def get_feedback_records() -> list[dict[str, Any]]:
    """Return all feedback records."""
    return _read_jsonl(FEEDBACK_FILE)


def get_average_latency() -> float:
    """Calculate average response latency."""
    records = get_monitoring_records()

    if not records:
        return 0.0

    latencies = [
        record["latency"]
        for record in records
        if isinstance(record.get("latency"), (int, float))
    ]

    if not latencies:
        return 0.0

    return round(sum(latencies) / len(latencies), 4)


def get_feedback_counts() -> dict[str, int]:
    """Return positive and negative feedback counts."""
    records = get_feedback_records()

    positive = sum(
        1 for record in records
        if record.get("rating") == "positive"
    )

    negative = sum(
        1 for record in records
        if record.get("rating") == "negative"
    )

    return {
        "positive": positive,
        "negative": negative,
    }


def get_query_count() -> int:
    """Return the total number of monitored queries."""
    return len(get_monitoring_records())


def get_category_counts() -> dict[str, int]:
    """Return the number of queries per category."""
    records = get_monitoring_records()

    counts: dict[str, int] = {}

    for record in records:
        category = record.get("category") or "unknown"
        counts[category] = counts.get(category, 0) + 1

    return counts


def get_monitoring_summary() -> dict[str, Any]:
    """
    Return a basic monitoring summary.

    This will later be used by the /api/metrics endpoint.
    """

    feedback = get_feedback_counts()

    return {
        "total_queries": get_query_count(),
        "average_latency": get_average_latency(),
        "positive_feedback": feedback["positive"],
        "negative_feedback": feedback["negative"],
        "categories": get_category_counts(),
    }


def get_queries_over_time() -> list[dict[str, Any]]:
    """
    Return the number of queries grouped by date.
    """
    records = get_monitoring_records()

    counts: dict[str, int] = {}

    for record in records:
        timestamp = record.get("timestamp")

        if not timestamp:
            continue

        try:
            date = datetime.fromisoformat(timestamp).date().isoformat()
        except ValueError:
            continue

        counts[date] = counts.get(date, 0) + 1

    return [
        {
            "date": date,
            "queries": count,
        }
        for date, count in sorted(counts.items())
    ]


def get_latency_over_time() -> list[dict[str, Any]]:
    """
    Return response latency grouped by date.
    """
    records = get_monitoring_records()

    result: list[dict[str, Any]] = []

    for record in records:
        timestamp = record.get("timestamp")
        latency = record.get("latency")

        if not timestamp or not isinstance(latency, (int, float)):
            continue

        try:
            date = datetime.fromisoformat(timestamp).date().isoformat()
        except ValueError:
            continue

        result.append(
            {
                "date": date,
                "latency": latency,
            }
        )

    return result


def get_score_metrics() -> dict[str, float]:
    """
    Calculate average retrieval and reranking scores.
    """
    records = get_monitoring_records()

    retrieval_scores = []
    rerank_scores = []

    for record in records:
        retrieval_scores.extend(
            score
            for score in record.get("retrieval_scores", [])
            if isinstance(score, (int, float))
        )

        rerank_scores.extend(
            score
            for score in record.get("rerank_scores", [])
            if isinstance(score, (int, float))
        )

    average_retrieval = (
        sum(retrieval_scores) / len(retrieval_scores)
        if retrieval_scores
        else 0.0
    )

    average_rerank = (
        sum(rerank_scores) / len(rerank_scores)
        if rerank_scores
        else 0.0
    )

    return {
        "average_retrieval_score": round(average_retrieval, 4),
        "average_rerank_score": round(average_rerank, 4),
    }


def get_metrics() -> dict[str, Any]:
    """
    Return all monitoring metrics used by the dashboard.
    """
    feedback = get_feedback_counts()
    scores = get_score_metrics()

    return {
        "overview": {
            "total_queries": get_query_count(),
            "average_latency": get_average_latency(),
            "positive_feedback": feedback["positive"],
            "negative_feedback": feedback["negative"],
        },
        "queries_over_time": get_queries_over_time(),
        "feedback": {
            "positive": feedback["positive"],
            "negative": feedback["negative"],
        },
        "latency_over_time": get_latency_over_time(),
        "scores": scores,
        "categories": get_category_counts(),
    }
